### ISSUE TITLE
Packages...

### ISSUE THREAD

**Issue by kitplummer** [kitlang/kit#84]
Have some time over this holiday period...want to contribute.  Have a lil bit of experience with FPM, figure I could pick up some of this card: https://trello.com/c/wRId5lB1/159-packages-installers - starting with the deb package.

A couple of questions:

Assuming I can build a package, where should it go?  Figuring back to GH Releases?  (https://docs.travis-ci.com/user/build-stages/deploy-github-releases/). Looks like there is only a master branch right now, so git/Github-flow aren't in play - so maybe just start with a continuous "alpha" build for now?

Any other dependencies besides gcc/clang required in the package dependency list that you can think of?

Sorry, wasn't sure best way to communicate these things.  If there is something better than here, just point me in the right direction.

**Comment by bendmorris** [comment]
Great! I had planned at some point to stop merging directly to master, let that be the main release line and use a `dev` branch for active development. We can go ahead and move to that model.

Github releases + a continuous alpha build seems like a good option for now. For the packages, `libyaml` is also a dependency.

If you want to discuss in real time: https://gitter.im/kitlang/kit otherwise issues are also fine.
